/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import Doctor.Doctor;
import Login.Login;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Duc Hoa
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label9 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        Reference = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        label2 = new java.awt.Label();
        NumofTablet = new javax.swing.JTextField();
        Dose = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        IssuedDate = new javax.swing.JTextField();
        Lot = new javax.swing.JTextField();
        DailyDose = new javax.swing.JTextField();
        ExpDate = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label18 = new java.awt.Label();
        FurtherInfor = new javax.swing.JTextField();
        label23 = new java.awt.Label();
        PossibleSide = new javax.swing.JTextField();
        label24 = new java.awt.Label();
        Admin = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        StoreAdvise = new javax.swing.JTextField();
        label30 = new java.awt.Label();
        HowtoUse = new javax.swing.JTextField();
        label31 = new java.awt.Label();
        DrivingUsingMachine = new javax.swing.JTextField();
        label32 = new java.awt.Label();
        DoctorNo = new javax.swing.JTextField();
        label33 = new java.awt.Label();
        PatientID = new javax.swing.JTextField();
        NameTablets = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Login = new javax.swing.JButton();

        label9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label9.setText("Reference No.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label1.setText("Name of Tables:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 60));

        Reference.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReferenceActionPerformed(evt);
            }
        });
        getContentPane().add(Reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 40));

        label8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label8.setText("Reference No:");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 80));

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label2.setText("Number of tablets:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 170, 100));

        NumofTablet.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NumofTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumofTabletActionPerformed(evt);
            }
        });
        getContentPane().add(NumofTablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 230, 40));

        Dose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoseActionPerformed(evt);
            }
        });
        getContentPane().add(Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, 40));

        label11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label11.setText("Dose:");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 100));

        IssuedDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        IssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuedDateActionPerformed(evt);
            }
        });
        getContentPane().add(IssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 230, 40));

        Lot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LotActionPerformed(evt);
            }
        });
        getContentPane().add(Lot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 40));

        DailyDose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DailyDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyDoseActionPerformed(evt);
            }
        });
        getContentPane().add(DailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 230, 40));

        ExpDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateActionPerformed(evt);
            }
        });
        getContentPane().add(ExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 230, 40));

        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label7.setText("Issued Date:");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 60, 100));

        label14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label14.setText("Lot:");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, 100));

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label15.setText("Daily Dose:");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 60, 90));

        label16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label16.setText("Exp Date:");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 60, 100));

        label18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label18.setText("Further Information:");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 170, 100));

        FurtherInfor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        FurtherInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurtherInforActionPerformed(evt);
            }
        });
        getContentPane().add(FurtherInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 220, 40));

        label23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label23.setText("Possible Side Effects:");
        getContentPane().add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 170, 100));

        PossibleSide.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PossibleSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PossibleSideActionPerformed(evt);
            }
        });
        getContentPane().add(PossibleSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 220, 40));

        label24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label24.setText("Adminstration:");
        getContentPane().add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 170, 100));

        Admin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 220, 40));

        label25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label25.setText("Stogare Advise:");
        getContentPane().add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 170, 100));

        StoreAdvise.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StoreAdvise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreAdviseActionPerformed(evt);
            }
        });
        getContentPane().add(StoreAdvise, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 220, 40));

        label30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label30.setText("How to Use Medication:");
        getContentPane().add(label30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 170, 100));

        HowtoUse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HowtoUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowtoUseActionPerformed(evt);
            }
        });
        getContentPane().add(HowtoUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 220, 40));

        label31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label31.setText("Driving Using Machines:");
        getContentPane().add(label31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 170, 100));

        DrivingUsingMachine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DrivingUsingMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivingUsingMachineActionPerformed(evt);
            }
        });
        getContentPane().add(DrivingUsingMachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 220, 40));

        label32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label32.setText("Doctors NHS No:");
        getContentPane().add(label32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 170, 100));

        DoctorNo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DoctorNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNoActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 220, 40));

        label33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label33.setText("Patient ID:");
        getContentPane().add(label33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 170, 100));

        PatientID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 220, 40));

        NameTablets.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        NameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(NameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 240, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No", "Lot", "Issued Date", "Exp Date", "Daily Dose", "Further Infor", "Store Advise", "Admin", "Driving Using Machine", "How to Use", "Patient ID", "Doctor No", "Possoble Side"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 1170, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 110, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, 30));

        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });
        jPanel1.add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 30));

        jButton5.setText("GP Appointment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 30));

        jButton6.setText("Pharmacy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 110, 30));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 1170, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReferenceActionPerformed

    private void NumofTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumofTabletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumofTabletActionPerformed

    private void DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoseActionPerformed

    private void IssuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuedDateActionPerformed

    private void LotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LotActionPerformed

    private void DailyDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DailyDoseActionPerformed

    private void ExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpDateActionPerformed

    private void FurtherInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurtherInforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FurtherInforActionPerformed

    private void PossibleSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PossibleSideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PossibleSideActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminActionPerformed

    private void StoreAdviseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreAdviseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StoreAdviseActionPerformed

    private void HowtoUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowtoUseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HowtoUseActionPerformed

    private void DrivingUsingMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivingUsingMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrivingUsingMachineActionPerformed

    private void DoctorNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNoActionPerformed

    private void PatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIDActionPerformed

    private void NameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTabletsActionPerformed
       if(NameTablets.getSelectedItem().equals("Ibuprofen")){           //Ibuprofen, Co-codamol, Paracetamol, Amlodipine
           Reference.setText("ACM001234");
           Dose.setText("2");
           NumofTablet.setText("23");
           Lot.setText("201900015");
           IssuedDate.setText("6/5/2018");
           ExpDate.setText("7/12/2019");
           DailyDose.setText("4");
           PossibleSide.setText("Bleeding");
           FurtherInfor.setText("Can Tho");
           StoreAdvise.setText("Les than 20%");
           Admin.setText("Yes, action");
           DrivingUsingMachine.setText("ACM001234");
           HowtoUse.setText("Use water, not alcohol");
           PatientID.setText("P0004");
           DoctorNo.setText("51236");
                     
       }
       else if(NameTablets.getSelectedItem().equals("Co-codamol")){
           Reference.setText("ACM001234");
           Dose.setText("4");
           NumofTablet.setText("24");
           Lot.setText("201900016");
           IssuedDate.setText("20/5/2018");
           ExpDate.setText("1/09/2019");
           DailyDose.setText("3");
           PossibleSide.setText("Sleeping");
           FurtherInfor.setText("Can Tho");
           StoreAdvise.setText("Les than 10%");
           Admin.setText("Yes, action");
           DrivingUsingMachine.setText("ACM001235");
           HowtoUse.setText("Read book");
           PatientID.setText("P0005");
           DoctorNo.setText("51237");
       }
       else if(NameTablets.getSelectedItem().equals("Paracetamol")){
           Reference.setText("ACM001236");
           Dose.setText("5");
           NumofTablet.setText("25");
           Lot.setText("201900015");
           IssuedDate.setText("01/09/2018");
           ExpDate.setText("26/12/2019");
           DailyDose.setText("4");
           PossibleSide.setText("Stomache hurt");
           FurtherInfor.setText("Can Tho");
           StoreAdvise.setText("None");
           Admin.setText("Yes, action");
           DrivingUsingMachine.setText("ACM001239");
           HowtoUse.setText("Don't eat spicy food");
           PatientID.setText("P0006");
           DoctorNo.setText("51236");
       }
       else if(NameTablets.getSelectedItem().equals("Amlodipine")){
           Reference.setText("ACM001237");
           Dose.setText("5");
           NumofTablet.setText("27");
           Lot.setText("201900015");
           IssuedDate.setText("6/5/2018");
           ExpDate.setText("7/12/2019");
           DailyDose.setText("4");
           PossibleSide.setText("Breathing");
           FurtherInfor.setText("Can Tho");
           StoreAdvise.setText("Les than 20%");
           Admin.setText("Yes, action");
           DrivingUsingMachine.setText("ACM001234");
           HowtoUse.setText("Eat rice");
           PatientID.setText("P0004");
           DoctorNo.setText("51236");
       }

    }//GEN-LAST:event_NameTabletsActionPerformed
        private JFrame frame;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
         frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Medical store billing", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() == -1){
            if(jTable1.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No data to delete!!!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Medical store billing", JOptionPane.OK_OPTION);
            }
        }
        else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteActionPerformed
    //UPDATE BUTTON
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        //if((NameTablets.getSelectedItem()).equals("Ibuprofen")){
            model.addRow(new Object[]{Reference.getText(), Reference.getText(), NumofTablet.getText(), NameTablets.getSelectedItem().toString(), 
            Lot.getText(), PossibleSide.getText(), FurtherInfor.getText(), StoreAdvise.getText(), IssuedDate.getText(), 
            ExpDate.getText(), DailyDose.getText(), Admin.getText(), DrivingUsingMachine.getText(), HowtoUse.getText(), 
            PatientID.getText(), DoctorNo.getText()});
            
        //}
        
    }//GEN-LAST:event_UpdateActionPerformed
    //
    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_DoctorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        Login myLogin = new Login();
        myLogin.setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admin;
    private javax.swing.JTextField DailyDose;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Doctor;
    private javax.swing.JTextField DoctorNo;
    private javax.swing.JTextField Dose;
    private javax.swing.JTextField DrivingUsingMachine;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField ExpDate;
    private javax.swing.JTextField FurtherInfor;
    private javax.swing.JTextField HowtoUse;
    private javax.swing.JTextField IssuedDate;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Lot;
    private javax.swing.JComboBox<String> NameTablets;
    private javax.swing.JTextField NumofTablet;
    private javax.swing.JTextField PatientID;
    private javax.swing.JTextField PossibleSide;
    private javax.swing.JTextField Reference;
    private javax.swing.JTextField StoreAdvise;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label11;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
