/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Doctor.Doctor;
import Pharmacy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Duc Hoa
 */
public class Login extends javax.swing.JFrame {
    int temp = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label16 = new java.awt.Label();
        label15 = new java.awt.Label();
        jtxtReference5 = new javax.swing.JTextField();
        jtxtReference12 = new javax.swing.JTextField();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        Password = new javax.swing.JPasswordField();
        Exit = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Cancle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        Office = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        Pharmacy = new javax.swing.JButton();
        Patient = new javax.swing.JButton();
        Payment = new javax.swing.JButton();
        GPA = new javax.swing.JButton();
        FeedBack = new javax.swing.JButton();
        Surgery = new javax.swing.JButton();
        Hospital = new javax.swing.JButton();
        Specialist = new javax.swing.JButton();
        Consultant = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Maintain = new javax.swing.JLabel();

        jButton13.setText("jButton13");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label16.setText("Exp Date:");
        jPanel1.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 150, 110));

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label15.setText("Daily Dose:");
        jPanel1.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 150, 100));

        jtxtReference5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jtxtReference5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReference5ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtReference5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 320, 50));

        jtxtReference12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jtxtReference12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReference12ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtReference12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 320, 50));

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label17.setText("Username");
        jPanel1.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 110));

        label18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label18.setText("Password");
        jPanel1.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 100));

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 290, 50));

        Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 130, 40));

        Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 130, 40));

        Cancle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cancle.setText("Cancle");
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });
        jPanel1.add(Cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 130, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Login Systems");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 80));

        Username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 290, 50));

        jRadioButton1.setText("jRadioButton1");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 810, 410));

        Office.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Office.setText("Office");
        Office.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficeActionPerformed(evt);
            }
        });
        getContentPane().add(Office, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 110, 40));

        Doctor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });
        getContentPane().add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 40));

        Pharmacy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Pharmacy.setText("Pharmacy");
        Pharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(Pharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 40));

        Patient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patient.setText("Patient");
        Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientActionPerformed(evt);
            }
        });
        getContentPane().add(Patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 40));

        Payment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Payment.setText("Payment");
        getContentPane().add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 40));

        GPA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GPA.setText("GPA");
        GPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAActionPerformed(evt);
            }
        });
        getContentPane().add(GPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 40));

        FeedBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FeedBack.setText("Feed back");
        getContentPane().add(FeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 120, 40));

        Surgery.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Surgery.setText("Surgery");
        getContentPane().add(Surgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 120, 40));

        Hospital.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Hospital.setText("Hospital");
        getContentPane().add(Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, 120, 40));

        Specialist.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Specialist.setText("Specialist");
        getContentPane().add(Specialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 300, 120, 40));

        Consultant.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Consultant.setText("Consultant");
        getContentPane().add(Consultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, 120, 40));

        Help.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Help.setText("Help");
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 120, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("MEDICAL STORE BILLING");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 1050, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Maintain.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Maintain.setText("Maintain");
        jPanel3.add(Maintain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 80, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 590, 80, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtReference5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtReference5ActionPerformed

    }//GEN-LAST:event_jtxtReference5ActionPerformed

    private void jtxtReference12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtReference12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtReference12ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void GPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAActionPerformed
        Pharmacy iPharmacy = new Pharmacy();
        iPharmacy.setVisible(true);
    }//GEN-LAST:event_GPAActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = Username.getText();
        String passwork = Password.getText();

        if (username.contains("User") && (passwork.contains("123"))) {
            Username.setText("");
            Password.setText("");

            Doctor.setEnabled(true);
            Pharmacy.setEnabled(true);
            Patient.setEnabled(true);
            Payment.setEnabled(true);
            GPA.setEnabled(true);
            Office.setEnabled(true);
            Surgery.setEnabled(true);
            Hospital.setEnabled(true);
            Specialist.setEnabled(true);
            Consultant.setEnabled(true);
            Help.setEnabled(true);
            FeedBack.setEnabled(true);
            Maintain.setEnabled(false);

        } else if (!(username.contains("User") && (passwork.contains("123")))) {
            Username.setText("");
            Password.setText("");

            Doctor.setEnabled(false);
            Pharmacy.setEnabled(false);
            Patient.setEnabled(false);
            Payment.setEnabled(false);
            GPA.setEnabled(false);
            Office.setEnabled(false);
            Surgery.setEnabled(false);
            Hospital.setEnabled(false);
            Specialist.setEnabled(false);
            Consultant.setEnabled(false);
            Help.setEnabled(false);
            FeedBack.setEnabled(false);
           Maintain.setEnabled(false);          
        }
        if ((username.contains("Admin") && (passwork.contains("123")))) {
            Username.setText("");
            Password.setText("");

            Doctor.setEnabled(true);
            Pharmacy.setEnabled(true);
            Patient.setEnabled(true);
            Payment.setEnabled(true);
            GPA.setEnabled(true);
            Office.setEnabled(true);
            Surgery.setEnabled(true);
            Hospital.setEnabled(true);
            Specialist.setEnabled(true);
            Consultant.setEnabled(true);
            Help.setEnabled(true);
            FeedBack.setEnabled(true);
            Maintain.setEnabled(true);
        }
        temp += 1;       
        if(temp == 3){
            System.exit(0); //ĐĂNG NHẬP 3 LẦN SAI CHƯƠNG TRÌNH TỰ ĐÓNG !!!
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Doctor.setEnabled(false);
        Pharmacy.setEnabled(false);
        Patient.setEnabled(false);
        Payment.setEnabled(false);
        GPA.setEnabled(false);
        Office.setEnabled(false);
        Surgery.setEnabled(false);
        Hospital.setEnabled(false);
        Specialist.setEnabled(false);
        Consultant.setEnabled(false);
        Help.setEnabled(false);
        FeedBack.setEnabled(false);
        Maintain.setEnabled(false);
        

    }//GEN-LAST:event_formWindowActivated

    private void PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientActionPerformed
        Pharmacy iPharmacy = new Pharmacy();
        iPharmacy.setVisible(true);
    }//GEN-LAST:event_PatientActionPerformed

    private JFrame frame;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Medical store billing", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        Username.setText("");
        Password.setText("");
    }//GEN-LAST:event_CancleActionPerformed

    private void PharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyActionPerformed
        Pharmacy myPharmacy = new Pharmacy();
        myPharmacy.setVisible(true);
    }//GEN-LAST:event_PharmacyActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_DoctorActionPerformed

    private void OfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficeActionPerformed
        Pharmacy iPharmacy = new Pharmacy();
        iPharmacy.setVisible(true);
    }//GEN-LAST:event_OfficeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancle;
    private javax.swing.JButton Consultant;
    private javax.swing.JButton Doctor;
    private javax.swing.JButton Exit;
    private javax.swing.JButton FeedBack;
    private javax.swing.JButton GPA;
    private javax.swing.JButton Help;
    private javax.swing.JButton Hospital;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Maintain;
    private javax.swing.JButton Office;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Patient;
    private javax.swing.JButton Payment;
    private javax.swing.JButton Pharmacy;
    private javax.swing.JButton Specialist;
    private javax.swing.JButton Surgery;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jtxtReference12;
    private javax.swing.JTextField jtxtReference5;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    // End of variables declaration//GEN-END:variables
}
