/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import Login.Login;
import Pharmacy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc Hoa
 */
public class Doctor extends javax.swing.JFrame {

    private JFrame frame;

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorRefNo = new java.awt.Label();
        label8 = new java.awt.Label();
        label2 = new java.awt.Label();
        LastName = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        Medicalname = new javax.swing.JTextField();
        PatiID = new javax.swing.JTextField();
        Poscode = new javax.swing.JTextField();
        Addresscen = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label18 = new java.awt.Label();
        Phone1 = new javax.swing.JTextField();
        label23 = new java.awt.Label();
        MedialCentralRef = new javax.swing.JTextField();
        label24 = new java.awt.Label();
        Fax = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        Phone2 = new javax.swing.JTextField();
        label30 = new java.awt.Label();
        PatienNum = new javax.swing.JTextField();
        label31 = new java.awt.Label();
        Email = new javax.swing.JTextField();
        label32 = new java.awt.Label();
        Patiensys = new javax.swing.JTextField();
        label33 = new java.awt.Label();
        PatienPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Pharmacy = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        DocNHSNo = new javax.swing.JTextField();
        ChoiceDoctor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DoctorRefNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoctorRefNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DoctorRefNo.setText("Doctor's Ref No:");
        getContentPane().add(DoctorRefNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 60));

        label8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label8.setText("Doctor NHS No:");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 80));

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label2.setText("Last name:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 100));

        LastName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 230, 40));

        FirstName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, 40));

        label11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label11.setText("First name:");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 100));

        Medicalname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Medicalname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalnameActionPerformed(evt);
            }
        });
        getContentPane().add(Medicalname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 230, 40));

        PatiID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PatiID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatiIDActionPerformed(evt);
            }
        });
        getContentPane().add(PatiID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 40));

        Poscode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Poscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoscodeActionPerformed(evt);
            }
        });
        getContentPane().add(Poscode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 230, 40));

        Addresscen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Addresscen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddresscenActionPerformed(evt);
            }
        });
        getContentPane().add(Addresscen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 230, 40));

        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label7.setText("Medical cental name:");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 180, 100));

        label14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label14.setText("Patient ID:");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 100));

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label15.setText("Post code:");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 80, 90));

        label16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label16.setText("Address central:");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 130, 100));

        label18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label18.setText("Phone 1:");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 80, 100));

        Phone1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone1ActionPerformed(evt);
            }
        });
        getContentPane().add(Phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 220, 40));

        label23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label23.setText("Medical central ref:");
        getContentPane().add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 170, 100));

        MedialCentralRef.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MedialCentralRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedialCentralRefActionPerformed(evt);
            }
        });
        getContentPane().add(MedialCentralRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 220, 40));

        label24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label24.setText("Fax NO:");
        getContentPane().add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 80, 100));

        Fax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaxActionPerformed(evt);
            }
        });
        getContentPane().add(Fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 220, 40));

        label25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label25.setText("Phone 2:");
        getContentPane().add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 80, 100));

        Phone2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone2ActionPerformed(evt);
            }
        });
        getContentPane().add(Phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 220, 40));

        label30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label30.setText("Patient NHS num:");
        getContentPane().add(label30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, 100));

        PatienNum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PatienNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatienNumActionPerformed(evt);
            }
        });
        getContentPane().add(PatienNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 220, 40));

        label31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label31.setText("Email address:");
        getContentPane().add(label31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 130, 100));

        Email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 220, 40));

        label32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label32.setText("Patient's symptom:");
        getContentPane().add(label32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, 100));

        Patiensys.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patiensys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatiensysActionPerformed(evt);
            }
        });
        getContentPane().add(Patiensys, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 220, 40));

        label33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label33.setText("Patient's phone:");
        getContentPane().add(label33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 140, 100));

        PatienPhone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PatienPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatienPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(PatienPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 220, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Ref No", "Doctor NHS No", "First Name", "Last Name", "Patient ID", "Medical cental name", "Address central", "Post code", "Medical central ref", "Phone 1 ", "Phone 2", "Fax", "Email address", "Patient's phone", "Patient's symptom"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 1170, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 110, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, 30));

        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });
        jPanel1.add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 30));

        jButton5.setText("GP Appointment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 30));

        Pharmacy.setText("Pharmacy");
        Pharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyActionPerformed(evt);
            }
        });
        jPanel1.add(Pharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 110, 30));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 1170, 90));

        DocNHSNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DocNHSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocNHSNoActionPerformed(evt);
            }
        });
        getContentPane().add(DocNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 40));

        ChoiceDoctor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ChoiceDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Ref", "P000123", "K111569", "J444256", "Q663112" }));
        ChoiceDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiceDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(ChoiceDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void MedicalnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalnameActionPerformed

    private void PatiIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatiIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatiIDActionPerformed

    private void PoscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoscodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoscodeActionPerformed

    private void AddresscenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddresscenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddresscenActionPerformed

    private void Phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone1ActionPerformed

    private void MedialCentralRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedialCentralRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedialCentralRefActionPerformed

    private void FaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaxActionPerformed

    private void Phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone2ActionPerformed

    private void PatienNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatienNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatienNumActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PatiensysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatiensysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatiensysActionPerformed

    private void PatienPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatienPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatienPhoneActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Medical store billing", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data to delete!!!");
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Medical store billing", JOptionPane.OK_OPTION);
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        //if((NameTablets.getSelectedItem()).equals("Ibuprofen")){
        model.addRow(new Object[]{DoctorRefNo.getText(), DoctorRefNo.getText(), LastName.getText(),
            PatiID.getText(), MedialCentralRef.getText(), Phone1.getText(), Phone2.getText(), Medicalname.getText(),
            Addresscen.getText(), Poscode.getText(), Fax.getText(), Email.getText(), PatienNum.getText(),
            PatienPhone.getText(), Patiensys.getText()});

        //}

    }//GEN-LAST:event_UpdateActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void PharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyActionPerformed
        Pharmacy iPharmacy = new Pharmacy();
        iPharmacy.setVisible(true);
    }//GEN-LAST:event_PharmacyActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        Login myLogin = new Login();
        myLogin.setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    private void DocNHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocNHSNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocNHSNoActionPerformed

    private void ChoiceDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoiceDoctorActionPerformed
        if (ChoiceDoctor.getSelectedItem().equals("P000123")) {           //Select Doctor's Ref, P000123, K111569, J444256, Q663112
            DocNHSNo.setText("Dr1440469");
            FirstName.setText("Paul");
            LastName.setText("Lee");
            PatiID.setText("201900015");
            Medicalname.setText("Sillicon Medical Central");
            Addresscen.setText("125/35/53/25 Yellow leaves street");
            Poscode.setText("CT135");
            MedialCentralRef.setText("HRC192168");
            Phone1.setText("0333333111");
            Phone2.setText("0111111264");
            Fax.setText("0209623154");
            Email.setText("HoaLDCE140469@fpt.edu.vn");
            PatienNum.setText("000-169");
            PatienPhone.setText("0789642158");
            Patiensys.setText("Sleep so much");

        } else if (ChoiceDoctor.getSelectedItem().equals("K111569")) {
            DocNHSNo.setText("Dr1440468");
            FirstName.setText("Hoa");
            LastName.setText("Lee");
            PatiID.setText("201900016");
            Medicalname.setText("Sillicon Medical Central");
            Addresscen.setText("125/35/53/25 Yellow leaves street");
            Poscode.setText("CT135");
            MedialCentralRef.setText("HRC192168");
            Phone1.setText("0256333222");
            Phone2.setText("0111231269");
            Fax.setText("0209458954");
            Email.setText("HoaLDCE140469@fpt.edu.vn");
            PatienNum.setText("000-169");
            PatienPhone.setText("078961258");
            Patiensys.setText("Can't Sleep");
        } else if (ChoiceDoctor.getSelectedItem().equals("J444256")) {
            DocNHSNo.setText("Dr1445669");
            FirstName.setText("Nuyc");
            LastName.setText("Hoy");
            PatiID.setText("225300151");
            Medicalname.setText("Sillicon Medical Central");
            Addresscen.setText("125/35/53/25 Yellow leaves street");
            Poscode.setText("CT135");
            MedialCentralRef.setText("HRC192168");
            Phone1.setText("033467981");
            Phone2.setText("0101211264");
            Fax.setText("0209784154");
            Email.setText("HoaLDCE140469@fpt.edu.vn");
            PatienNum.setText("000-987");
            PatienPhone.setText("0654142158");
            Patiensys.setText("Easy Cry");
        } else if (ChoiceDoctor.getSelectedItem().equals("Q663112")) {
            DocNHSNo.setText("Dr1423669");
            FirstName.setText("Depvl");
            LastName.setText("Sthoy");
            PatiID.setText("225213151");
            Medicalname.setText("Sillicon Medical Central");
            Addresscen.setText("125/35/53/25 Yellow leaves street");
            Poscode.setText("CT135");
            MedialCentralRef.setText("HRC192168");
            Phone1.setText("033014781");
            Phone2.setText("0175632164");
            Fax.setText("0209784154");
            Email.setText("HoaLDCE140469@fpt.edu.vn");
            PatienNum.setText("000-925");
            PatienPhone.setText("0651235158");
            Patiensys.setText("Vomiting");
        } else if (ChoiceDoctor.getSelectedItem().equals("Select Doctor's Ref")) {
            DocNHSNo.setText("");
            FirstName.setText("");
            LastName.setText("");
            PatiID.setText("");
            Medicalname.setText("");
            Addresscen.setText("");
            Poscode.setText("");
            MedialCentralRef.setText("");
            Phone1.setText("");
            Phone2.setText("");
            Fax.setText("");
            Email.setText("");
            PatienNum.setText("");
            PatienPhone.setText("");
            Patiensys.setText("");
        }
    }//GEN-LAST:event_ChoiceDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addresscen;
    private javax.swing.JComboBox<String> ChoiceDoctor;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DocNHSNo;
    private javax.swing.JButton Doctor;
    private java.awt.Label DoctorRefNo;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Fax;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton Login;
    private javax.swing.JTextField MedialCentralRef;
    private javax.swing.JTextField Medicalname;
    private javax.swing.JTextField PatiID;
    private javax.swing.JTextField PatienNum;
    private javax.swing.JTextField PatienPhone;
    private javax.swing.JTextField Patiensys;
    private javax.swing.JButton Pharmacy;
    private javax.swing.JTextField Phone1;
    private javax.swing.JTextField Phone2;
    private javax.swing.JTextField Poscode;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label11;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
